apiVersion: v1
kind: ConfigMap
metadata:
  name: food-delivery-config
  namespace: food-delivery
data:
  USER_SERVICE_URL: "http://user-service:8081"
  FOOD_SERVICE_URL: "http://food-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8084"
  RABBITMQ_URL: "amqp://guest:guest@host.docker.internal:5672/"
