apiVersion: v1
kind: Secret
metadata:
  name: food-delivery-secrets
  namespace: food-delivery
type: Opaque
stringData:
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  DATABASE_PASSWORD: "postgres"
  JWT_SECRET: "secret-key"
  STRIPE_SECRET_KEY: "sk_test_xxx"
  STRIPE_WEBHOOK_SECRET: "whsec_xxx"