apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: food-delivery
  labels:
    app: user-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: food-delivery-config
            - secretRef:
                name: food-delivery-secrets
          env:
            - name: DB_URL
              value: "postgres://postgres:postgres@host.docker.internal:5432/go-user-db"
          resources:
            requests:
              memory: "64Mi"
              cpu: "256m"
            limits:
              memory: "128Mi"
              cpu: "512m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
